version: "3.8"

services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - REPO=${REPO:-}
      - ORGANIZATION=${ORGANIZATION:-}
      - REG_TOKEN=${REG_TOKEN}
      - NAME=${NAME:-runner-${HOSTNAME}}
      - WORK_DIR=${WORK_DIR:-_work}
      - LABELS=${LABELS:-}
      - RUNNER_GROUP=${RUNNER_GROUP:-Default}
      - REPLACE_EXISTING=${REPLACE_EXISTING:-true}
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
        reservations:
          cpus: "0.4"
          memory: 256M
