version: "3.8"

services:
    github-runner:
        image: milangress/github-runner-docker:latest
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        privileged: true
        user: "0:0" # Run as root for Docker daemon
        # No socket mount - runs its own Docker daemon inside container
        environment:
            - REPO=${REPO:-}
            - ORGANIZATION=${ORGANIZATION:-}
            - REG_TOKEN=${REG_TOKEN:-}
            - GITHUB_TOKEN=${GITHUB_TOKEN:-}
            - NAME=${NAME:-runner-${HOSTNAME}}
            - WORK_DIR=${WORK_DIR:-_work}
            - LABELS=${LABELS:-docker-in-docker,buildx}
            - RUNNER_GROUP=${RUNNER_GROUP:-Default}
            - REPLACE_EXISTING=${REPLACE_EXISTING:-true}
        volumes:
            # Docker storage for the internal daemon
            - docker-storage:/var/lib/docker
            # Buildx cache for faster rebuilds
            - buildx-cache:/root/.cache/buildx
        healthcheck:
            test: ["CMD", "/healthcheck.sh"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 60s # Longer start period for Docker daemon
        deploy:
            resources:
                limits:
                    cpus: "4" # Even more CPU for multi-platform Rust builds
                    memory: 8G # More memory for QEMU emulation + Rust builds
                reservations:
                    cpus: "0.5"
                    memory: 1G

volumes:
    docker-storage:
    buildx-cache:
