version: "3.8"

services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - REPO=${REPO:-}
      - ORGANIZATION=${ORGANIZATION:-}
      - REG_TOKEN=${REG_TOKEN}
      - NAME=${NAME:-runner-${HOSTNAME}}
      - WORK_DIR=${WORK_DIR:-_work}
      - LABELS=${LABELS:-}
      - RUNNER_GROUP=${RUNNER_GROUP:-Default}
      - REPLACE_EXISTING=${REPLACE_EXISTING:-true}
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
        reservations:
          cpus: "0.4"
          memory: 256M
